{
 "title": "PgBouncer",
 "description": "A visual representation of Prometheus metrics collected from PgBouncer servers.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "mstdn.party : 172.16.30.12:9127, mstdn.plus : 172.16.30.13:9127"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(pgbouncer_up, instance)"
   },
   {
    "name": "port",
    "query": "label_values(pgbouncer_up, instance)"
   },
   {
    "name": "db",
    "label": "Db",
    "query": "label_values(pgbouncer_databases_current_connections,database)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(pgbouncer_up, service)"
   },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "PgBouncer Overview ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Active database connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_databases_current_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "{{database}},{{service}}"
    }
   ]
  },
  {
   "title": "Client active connections $db",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer_pools_client_active_connections{database=~\"$db\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Queries per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stats_totals_queries_pooled_total{database=~\"$db\", instance=~\"$instance\"}[5m]))"
    }
   ]
  },
  {
   "title": "Average time per transaction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_totals_server_in_transaction_seconds_total{database=~\"$db\", instance=~\"$instance\"}/pgbouncer_stats_totals_sql_transactions_pooled_total{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Transactions duration microseconds"
    }
   ]
  },
  {
   "title": "Connection wait time total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_totals_client_wait_seconds_total{database=~\"$db\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Average time per query",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer_stats_totals_queries_duration_seconds_total{database=~\"$db\", instance=~\"$instance\"} / pgbouncer_stats_totals_queries_pooled_total{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Transactions duration microseconds"
    }
   ]
  },
  { "title": "PgBouncer Details ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }, "repeat": "instance" },
  {
   "title": "Average Query Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer_stats_totals_queries_duration_seconds_total{instance=~\"$instance\", database=~\"$db\"}/pgbouncer_stats_totals_queries_pooled_total{instance=~\"$instance\", database=~\"$db\"}",
     "legendFormat": "Time spent running query"
    },
    {
     "expr": "pgbouncer_stats_totals_server_in_transaction_seconds_total{instance=~\"$instance\", database=~\"$db\"}/pgbouncer_stats_totals_sql_transactions_pooled_total{instance=~\"$instance\", database=~\"$db\"}",
     "legendFormat": "Time spent in transaction"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_server_active_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Server active connections"
    },
    {
     "expr": "pgbouncer_pools_server_active_cancel_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Server active cancel connections"
    },
    {
     "expr": "pgbouncer_pools_server_being_canceled_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Server being cancelled connections"
    },
    {
     "expr": "pgbouncer_pools_server_idle_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Server idle connections"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Server login connections"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Server testing connections"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Server used connections"
    }
   ]
  },
  {
   "title": "Average queries per transaction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "pgbouncer_stats_totals_queries_pooled_total{instance=~\"$instance\", database=~\"$db\"}/pgbouncer_stats_totals_sql_transactions_pooled_total{instance=~\"$instance\", database=~\"$db\"}",
     "legendFormat": "Queries per transaction"
    }
   ]
  },
  {
   "title": "Idle in transaction time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(pgbouncer_stats_totals_queries_duration_seconds_total{instance=~\"$instance\", database=~\"$db\"}/pgbouncer_stats_totals_server_in_transaction_seconds_total{instance=~\"$instance\", database=~\"$db\"})",
     "legendFormat": "1 - total_query_time / total_xact_time"
    }
   ]
  },
  {
   "title": "Incoming/outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-rate(pgbouncer_stats_totals_sent_bytes_total{database=~\"$db\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Sent Bytes"
    },
    {
     "expr": "rate(pgbouncer_stats_totals_received_bytes_total{database=~\"$db\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Client active connections "
    },
    {
     "expr": "pgbouncer_pools_client_waiting_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Client waiting connections"
    },
    {
     "expr": "pgbouncer_pools_client_active_cancel_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Client cancel connections"
    },
    {
     "expr": "pgbouncer_pools_client_waiting_cancel_connections{database=~\"$db\", instance=~\"$instance\"}",
     "legendFormat": "Client waiting cancel connections"
    }
   ]
  }
 ]
}